### ISSUE TITLE
trying to deploy on heroku, but need some help

### ISSUE THREAD

**Issue by marcmoo** [shoumma/ReForum#6]
Hi Shouma,
i was tring to deploying it to heroku too but i found a problem even though it shows deployed succeed:
"An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details".( message on heroku)

everything working good on dev mode.

i also get it run on heroku bash, it shows same error as it was in logs:

Error: Cannot find module 'async/each'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/server.js:6:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TuGaiForum@1.0.0 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TuGaiForum@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-12-25T21_09_40_574Z-debug.log

my repo is here:

https://github.com/gogogous88/reforum

please help thank you!

**Comment by marcmoo** [comment]
still cannot figure out. any tricky small tips? really appreciate with it!

**Comment by marcmoo** [comment]
shoumma, i've figured it out finally. I had done following steps:
to solve the problem of above errors in terminal run `$heroku config:set NODE_MODULES_CACHE=false` then run `git commit -am 'disable node_modules cache' --allow-empty`
then run `git push heroku master`

and now it can be pused but still i got heroku logs showing i got R10, H10, H20(time out errors), following are what i do to solve it:

1. Create a file name exactly `Procfile` (no .txt, no. js just a file name Procfile in root directory.
2. put following codes in Procfile: `node server.js`
3. in terminal run` heroku ps:scale web=1` (or you can activate your dyno in the heroku management panel)
4. `git add . `then `git commit -m 'something here'` then `git push heroku master` then i got my website hosted on heroku! yeah~~~~

**Comment by seriousbee** [comment]
Hi there! 

I was also experiencing a lot of issues with deployment, but what has worked for me is getting rid of this line:
https://github.com/shoumma/ReForum/blob/16117b77761d4044d99e784d82e187f079f56801/package.json#L37
Heroku dynamically assigns the port so hardcoding it here is not a great idea :)

Cheers!

**Comment by thebkr7** [comment]
@seriousbee When I remove that line it fails to build. Did you do anything else?
