### ISSUE TITLE
set up on local server fail

### ISSUE THREAD

**Issue by poioit** [shoumma/ReForum#7]
When I set up on my local server, after github OAuth, it shows the message:

This site can’t be reached
localhost unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_CLOSED

I don't know what configuration is missing.

I have set up my credentials.js like this
  GITHUB_CLIENT_ID: '331c575bfb5220a7dee1',
  GITHUB_CLIENT_SECRET: 'acc5fcc768b952382d60a27e830f1447b391ee2a',
  GITHUB_CALLBACK_URL: 'https://localhost:3030/api/user/authViaGitHub/callback',

can you give me some hint what's going wrong.

**Comment by poioit** [comment]
I found out that I should set 'http' instead of 'https'
https doesn't work.

**Comment by xiaoniao000** [comment]
I ran into the same problem and used your method to solve it correctly, thank you

> I found out that I should set 'http' instead of 'https'
> https doesn't work.
