### ISSUE TITLE
Showing "Sorry, couldn't find the forum." all the time

### ISSUE THREAD

**Issue by YoungNK** [shoumma/ReForum#8]
I deploy the forum on my mbp.
then auth with my github account,but Showing "Sorry, couldn't find the forum." all the time

**Comment by maciejso** [comment]
Get get passed this stage too.

**Comment by aayush801** [comment]
> I deploy the forum on my mbp.
> then auth with my github account,but Showing "Sorry, couldn't find the forum." all the time

hey did you figure this out?
